#!/bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --right-of DisplayPort-0

	bspc monitor DisplayPort-0 -d 1 2 3 4
	bspc monitor HDMI-A-0 -d 5 6 7 8

bspc rule -a Spotify desktop=^6

bspc config border_width  0
bspc config window_gap    15
bspc config split_ratio   0.52
bspc config top_padding	  0
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0

~/.fehbg &

$HOME/.config/polybar/launch.sh

