#!/bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then
	xrandr --output HDMI2 --mode 1920x1080 --rotate normal --output eDP1 --primary --mode 1920x1080 --rotate normal --below HDMI2

	bspc monitor HDMI2 -d 1 2 3 4
	bspc monitor eDP1 -d 5 6 7 8
else
	bspc monitor eDP1 -d 1 2 3 4 
fi

bspc config border_width  0
bspc config window_gap    18
bspc config split_ratio   0.50
bspc config top_padding	  0
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0
#bspc config focused_border_color "#F0C674"
#bspc config normal_border_color "#C5C8C6"

$HOME/.config/polybar/launch.sh

